// Code generated by protoc-gen-go.
// source: grpc_data.proto
// DO NOT EDIT!

/*
Package esigrpc is a generated protocol buffer package.

It is generated from these files:
	grpc_data.proto

It has these top-level messages:
	ResourceArgs
	HeaderBody
*/
package esigrpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ResourceArg same as backend.ResourceArgs but stripped of some fields for
// security reasons.
type ResourceArgs struct {
	ExternalReq      *ResourceArgs_ExternalReq `protobuf:"bytes,1,opt,name=external_req,json=externalReq" json:"external_req,omitempty"`
	Url              string                    `protobuf:"bytes,2,opt,name=url" json:"url,omitempty"`
	MaxBodySize      uint64                    `protobuf:"varint,3,opt,name=max_body_size,json=maxBodySize" json:"max_body_size,omitempty"`
	Key              string                    `protobuf:"bytes,4,opt,name=key" json:"key,omitempty"`
	ReturnHeaders    []string                  `protobuf:"bytes,5,rep,name=return_headers,json=returnHeaders" json:"return_headers,omitempty"`
	ReturnHeadersAll bool                      `protobuf:"varint,6,opt,name=return_headers_all,json=returnHeadersAll" json:"return_headers_all,omitempty"`
}

func (m *ResourceArgs) Reset()                    { *m = ResourceArgs{} }
func (m *ResourceArgs) String() string            { return proto.CompactTextString(m) }
func (*ResourceArgs) ProtoMessage()               {}
func (*ResourceArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ResourceArgs) GetExternalReq() *ResourceArgs_ExternalReq {
	if m != nil {
		return m.ExternalReq
	}
	return nil
}

func (m *ResourceArgs) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *ResourceArgs) GetMaxBodySize() uint64 {
	if m != nil {
		return m.MaxBodySize
	}
	return 0
}

func (m *ResourceArgs) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ResourceArgs) GetReturnHeaders() []string {
	if m != nil {
		return m.ReturnHeaders
	}
	return nil
}

func (m *ResourceArgs) GetReturnHeadersAll() bool {
	if m != nil {
		return m.ReturnHeadersAll
	}
	return false
}

type ResourceArgs_ExternalReq struct {
	Method           string   `protobuf:"bytes,1,opt,name=method" json:"method,omitempty"`
	Url              string   `protobuf:"bytes,2,opt,name=url" json:"url,omitempty"`
	Proto            string   `protobuf:"bytes,3,opt,name=proto" json:"proto,omitempty"`
	ProtoMajor       int32    `protobuf:"varint,4,opt,name=proto_major,json=protoMajor" json:"proto_major,omitempty"`
	ProtoMinor       int32    `protobuf:"varint,5,opt,name=proto_minor,json=protoMinor" json:"proto_minor,omitempty"`
	Header           []string `protobuf:"bytes,6,rep,name=header" json:"header,omitempty"`
	ContentLength    int64    `protobuf:"varint,7,opt,name=ContentLength" json:"ContentLength,omitempty"`
	TransferEncoding []string `protobuf:"bytes,8,rep,name=transfer_encoding,json=transferEncoding" json:"transfer_encoding,omitempty"`
	Close            bool     `protobuf:"varint,9,opt,name=close" json:"close,omitempty"`
	Host             string   `protobuf:"bytes,10,opt,name=host" json:"host,omitempty"`
	RemoteAddr       string   `protobuf:"bytes,11,opt,name=remote_addr,json=remoteAddr" json:"remote_addr,omitempty"`
	RealIp           string   `protobuf:"bytes,12,opt,name=real_ip,json=realIp" json:"real_ip,omitempty"`
	RequestUri       string   `protobuf:"bytes,13,opt,name=request_uri,json=requestUri" json:"request_uri,omitempty"`
	Form             []byte   `protobuf:"bytes,14,opt,name=form,proto3" json:"form,omitempty"`
}

func (m *ResourceArgs_ExternalReq) Reset()                    { *m = ResourceArgs_ExternalReq{} }
func (m *ResourceArgs_ExternalReq) String() string            { return proto.CompactTextString(m) }
func (*ResourceArgs_ExternalReq) ProtoMessage()               {}
func (*ResourceArgs_ExternalReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *ResourceArgs_ExternalReq) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *ResourceArgs_ExternalReq) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *ResourceArgs_ExternalReq) GetProto() string {
	if m != nil {
		return m.Proto
	}
	return ""
}

func (m *ResourceArgs_ExternalReq) GetProtoMajor() int32 {
	if m != nil {
		return m.ProtoMajor
	}
	return 0
}

func (m *ResourceArgs_ExternalReq) GetProtoMinor() int32 {
	if m != nil {
		return m.ProtoMinor
	}
	return 0
}

func (m *ResourceArgs_ExternalReq) GetHeader() []string {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ResourceArgs_ExternalReq) GetContentLength() int64 {
	if m != nil {
		return m.ContentLength
	}
	return 0
}

func (m *ResourceArgs_ExternalReq) GetTransferEncoding() []string {
	if m != nil {
		return m.TransferEncoding
	}
	return nil
}

func (m *ResourceArgs_ExternalReq) GetClose() bool {
	if m != nil {
		return m.Close
	}
	return false
}

func (m *ResourceArgs_ExternalReq) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *ResourceArgs_ExternalReq) GetRemoteAddr() string {
	if m != nil {
		return m.RemoteAddr
	}
	return ""
}

func (m *ResourceArgs_ExternalReq) GetRealIp() string {
	if m != nil {
		return m.RealIp
	}
	return ""
}

func (m *ResourceArgs_ExternalReq) GetRequestUri() string {
	if m != nil {
		return m.RequestUri
	}
	return ""
}

func (m *ResourceArgs_ExternalReq) GetForm() []byte {
	if m != nil {
		return m.Form
	}
	return nil
}

// HeaderBody a return value like in the backend package but here the three
// return arguments are combined into one struct. If error is empty, then no
// error has happend.
type HeaderBody struct {
	Header []string `protobuf:"bytes,1,rep,name=header" json:"header,omitempty"`
	Body   []byte   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
}

func (m *HeaderBody) Reset()                    { *m = HeaderBody{} }
func (m *HeaderBody) String() string            { return proto.CompactTextString(m) }
func (*HeaderBody) ProtoMessage()               {}
func (*HeaderBody) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HeaderBody) GetHeader() []string {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *HeaderBody) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto.RegisterType((*ResourceArgs)(nil), "esigrpc.ResourceArgs")
	proto.RegisterType((*ResourceArgs_ExternalReq)(nil), "esigrpc.ResourceArgs.ExternalReq")
	proto.RegisterType((*HeaderBody)(nil), "esigrpc.HeaderBody")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for HeaderBodyService service

type HeaderBodyServiceClient interface {
	GetHeaderBody(ctx context.Context, in *ResourceArgs, opts ...grpc.CallOption) (*HeaderBody, error)
}

type headerBodyServiceClient struct {
	cc *grpc.ClientConn
}

func NewHeaderBodyServiceClient(cc *grpc.ClientConn) HeaderBodyServiceClient {
	return &headerBodyServiceClient{cc}
}

func (c *headerBodyServiceClient) GetHeaderBody(ctx context.Context, in *ResourceArgs, opts ...grpc.CallOption) (*HeaderBody, error) {
	out := new(HeaderBody)
	err := grpc.Invoke(ctx, "/esigrpc.HeaderBodyService/GetHeaderBody", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for HeaderBodyService service

type HeaderBodyServiceServer interface {
	GetHeaderBody(context.Context, *ResourceArgs) (*HeaderBody, error)
}

func RegisterHeaderBodyServiceServer(s *grpc.Server, srv HeaderBodyServiceServer) {
	s.RegisterService(&_HeaderBodyService_serviceDesc, srv)
}

func _HeaderBodyService_GetHeaderBody_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourceArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HeaderBodyServiceServer).GetHeaderBody(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/esigrpc.HeaderBodyService/GetHeaderBody",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HeaderBodyServiceServer).GetHeaderBody(ctx, req.(*ResourceArgs))
	}
	return interceptor(ctx, in, info, handler)
}

var _HeaderBodyService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "esigrpc.HeaderBodyService",
	HandlerType: (*HeaderBodyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHeaderBody",
			Handler:    _HeaderBodyService_GetHeaderBody_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc_data.proto",
}

func init() { proto.RegisterFile("grpc_data.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 511 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0xcd, 0x6e, 0xd3, 0x4c,
	0x14, 0xfd, 0xfc, 0xe5, 0xa7, 0xcd, 0x75, 0x5c, 0xda, 0xe1, 0x6f, 0xe8, 0x06, 0x13, 0x81, 0x64,
	0x89, 0xca, 0x8b, 0xb2, 0x61, 0xc3, 0xa2, 0x2d, 0x11, 0x54, 0x02, 0xa9, 0x9a, 0x88, 0xb5, 0x35,
	0xf5, 0xdc, 0xc4, 0xa6, 0xb6, 0x27, 0xb9, 0x1e, 0xa3, 0xa4, 0x2f, 0xc0, 0x03, 0xf0, 0xc2, 0x68,
	0xc6, 0x29, 0x71, 0xa4, 0xee, 0xee, 0x39, 0x3e, 0x67, 0x7c, 0xee, 0x0f, 0x3c, 0x59, 0xd0, 0x32,
	0x4d, 0x94, 0x34, 0x32, 0x5e, 0x92, 0x36, 0x9a, 0x1d, 0x60, 0x9d, 0x5b, 0x6e, 0xf2, 0x7b, 0x00,
	0x63, 0x81, 0xb5, 0x6e, 0x28, 0xc5, 0x0b, 0x5a, 0xd4, 0xec, 0x33, 0x8c, 0x71, 0x6d, 0x90, 0x2a,
	0x59, 0x24, 0x84, 0x2b, 0xee, 0x85, 0x5e, 0xe4, 0x9f, 0xbf, 0x89, 0xb7, 0x86, 0xb8, 0x2b, 0x8e,
	0xa7, 0x5b, 0xa5, 0xc0, 0x95, 0xf0, 0x71, 0x07, 0xd8, 0x31, 0xf4, 0x1a, 0x2a, 0xf8, 0xff, 0xa1,
	0x17, 0x8d, 0x84, 0x2d, 0xd9, 0x04, 0x82, 0x52, 0xae, 0x93, 0x5b, 0xad, 0x36, 0x49, 0x9d, 0xdf,
	0x23, 0xef, 0x85, 0x5e, 0xd4, 0x17, 0x7e, 0x29, 0xd7, 0x97, 0x5a, 0x6d, 0x66, 0xf9, 0x3d, 0x5a,
	0xd7, 0x1d, 0x6e, 0x78, 0xbf, 0x75, 0xdd, 0xe1, 0x86, 0xbd, 0x83, 0x23, 0x42, 0xd3, 0x50, 0x95,
	0x64, 0x28, 0x15, 0x52, 0xcd, 0x07, 0x61, 0x2f, 0x1a, 0x89, 0xa0, 0x65, 0xbf, 0xb6, 0x24, 0x3b,
	0x03, 0xb6, 0x2f, 0x4b, 0x64, 0x51, 0xf0, 0x61, 0xe8, 0x45, 0x87, 0xe2, 0x78, 0x4f, 0x7a, 0x51,
	0x14, 0xa7, 0x7f, 0x7a, 0xe0, 0x77, 0x92, 0xb3, 0x17, 0x30, 0x2c, 0xd1, 0x64, 0x5a, 0xb9, 0x66,
	0x47, 0x62, 0x8b, 0x1e, 0x69, 0xe2, 0x19, 0x0c, 0xdc, 0xfc, 0x5c, 0xf8, 0x91, 0x68, 0x01, 0x7b,
	0x0d, 0xbe, 0x2b, 0x92, 0x52, 0xfe, 0xd4, 0xe4, 0xe2, 0x0f, 0x04, 0x38, 0xea, 0xbb, 0x65, 0x3a,
	0x82, 0xbc, 0xd2, 0xc4, 0x07, 0x5d, 0x81, 0x65, 0x6c, 0x82, 0x36, 0x38, 0x1f, 0xba, 0xf6, 0xb6,
	0x88, 0xbd, 0x85, 0xe0, 0x4a, 0x57, 0x06, 0x2b, 0xf3, 0x0d, 0xab, 0x85, 0xc9, 0xf8, 0x41, 0xe8,
	0x45, 0x3d, 0xb1, 0x4f, 0xb2, 0xf7, 0x70, 0x62, 0x48, 0x56, 0xf5, 0x1c, 0x29, 0xc1, 0x2a, 0xd5,
	0x2a, 0xaf, 0x16, 0xfc, 0xd0, 0x3d, 0x74, 0xfc, 0xf0, 0x61, 0xba, 0xe5, 0x6d, 0x0b, 0x69, 0xa1,
	0x6b, 0xe4, 0x23, 0x37, 0x9d, 0x16, 0x30, 0x06, 0xfd, 0x4c, 0xd7, 0x86, 0x83, 0xeb, 0xcb, 0xd5,
	0x36, 0x35, 0x61, 0xa9, 0x0d, 0x26, 0x52, 0x29, 0xe2, 0xbe, 0xfb, 0x04, 0x2d, 0x75, 0xa1, 0x14,
	0xb1, 0x97, 0x70, 0x40, 0x28, 0x8b, 0x24, 0x5f, 0xf2, 0x71, 0x3b, 0x38, 0x0b, 0xaf, 0x97, 0xad,
	0x73, 0xd5, 0x60, 0x6d, 0x92, 0x86, 0x72, 0x1e, 0x3c, 0x38, 0x1d, 0xf5, 0x83, 0x72, 0xfb, 0xbb,
	0xb9, 0xa6, 0x92, 0x1f, 0x85, 0x5e, 0x34, 0x16, 0xae, 0x9e, 0x7c, 0x04, 0x68, 0x77, 0x64, 0xcf,
	0xa1, 0x33, 0x11, 0x6f, 0x6f, 0x22, 0x0c, 0xfa, 0xf6, 0x84, 0xdc, 0x52, 0xc6, 0xc2, 0xd5, 0xe7,
	0x02, 0x4e, 0x76, 0xce, 0x19, 0xd2, 0xaf, 0x3c, 0x45, 0xf6, 0x09, 0x82, 0x2f, 0x68, 0x3a, 0x2f,
	0x3e, 0x7f, 0xf4, 0x84, 0x4f, 0x9f, 0xfe, 0xa3, 0x77, 0xda, 0xc9, 0x7f, 0x97, 0x67, 0xf0, 0x6a,
	0x5e, 0xc6, 0x75, 0x9a, 0x35, 0xa5, 0x4c, 0x33, 0xa4, 0x79, 0x19, 0xa7, 0x52, 0xa9, 0x8d, 0x55,
	0x5f, 0x06, 0x57, 0xb6, 0x9c, 0xce, 0xae, 0x6f, 0xec, 0x0a, 0x6f, 0xbc, 0xdb, 0xa1, 0xdb, 0xe5,
	0x87, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x42, 0x37, 0xd3, 0x78, 0x68, 0x03, 0x00, 0x00,
}
